name: Go workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lztd1/golangstudy/golangstudy
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Display Go version
        run: go version
      - name: Install deps
        run: go mod download
      - name: try build
        run: go build ./cmd/main.go
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: ['build']
    steps:
      - uses: actions/checkout@v4
      - name: push into grc.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true
